apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-manager.fullname" . }}-db-secrets
  labels:
    {{- include "nginx-manager.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  clickhouse-password: {{ .Values.clickhouse.password | b64enc | quote }}
---
{{- if .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-manager.fullname" . }}-vault-secrets
  labels:
    {{- include "nginx-manager.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.vault.token | b64enc | quote }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-manager.fullname" . }}-otel-config
  labels:
    {{- include "nginx-manager.labels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      clickhouse:
        endpoint: "tcp://{{ .Release.Name }}-clickhouse:9000?database=nginx_analytics"
        username: "default"
        # Password injected via environment variable CLICKHOUSE_PASSWORD
        password: ${env:CLICKHOUSE_PASSWORD}
        timeout: 5s
        retry_on_failure:
          enabled: true
      logging:
        loglevel: debug

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse, logging]
