apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    url: http://avika-clickhouse:8123
    jsonData:
      defaultDatabase: nginx_analytics
      protocol: http
      port: 8123
    editable: true
