apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: avika

resources:
  - keycloak-postgres.yaml
  - keycloak-realm-config.yaml
  - keycloak-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: avika-identity
